# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a8117e40c8593d8e706db4f6e2185c5c943d43a7556f92689604fb00e03945fba5d11af6fd8edf825dbf3ae37a44d2732701f709bc1a390ddf18a2dff76f17

test:
  secret_key_base: bdd19ebcfc93bb247385bfb558f21e359f4ead33793b2a27cf58e373832339c9937e25ce6c7752da243ae09038d7fa5c3af5c846b3fa345621cdfb3872edd368

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
